version: 0.2
  
env:
  variables:
    TF_VERSION: "0.15.5"
  
phases:
  
  install:
    commands:
      - cd /usr/bin  
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"  
      - unzip -o terraform.zip

  pre_build:
    commands:
      - if [ $TF_STAGE = "apply" ]; then echo "Copying $CODEBUILD_SRC_DIR_TerraformPlan/${TF_PLAN_FILE_NAME} to $CODEBUILD_SRC_DIR" ; cp -r $CODEBUILD_SRC_DIR_TerraformPlan/${TF_PLAN_FILE_NAME} $CODEBUILD_SRC_DIR ; fi
  
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - sed -i -e "s/{{ENV}}/$TF_VAR_ENV/" terraform.tf
      - terraform init -no-color
      - terraform $TF_ACTION -no-color
  
  post_build:
    commands:
      - echo "terraform $TF_ACTION on $TF_VAR_ENV completed"
      
artifacts:
  name: TerraformPlan
  discard-paths: yes
  files:
    - ${TF_PLAN_FILE_NAME}