ENV                                = "dani-s-test"
EMAIL_ENDPOINT                     = "daniyal@eurustechnologies.com"
ENABLE_FEEDBACK_SUBMISSION         = "true"
CIDR_BLOCK                         = "11.0.0.0/16"
PRIVATE_SUBNETS                    = "6"
PUBLIC_SUBNETS                     = "3"
ENABLE_VPC_FLOW_LOGS_IN_CLOUDWATCH = true
ENABLE_VPC_FLOW_LOGS_IN_BUCKET     = true
kms_deletion_windows_in_days       = 7
create_regional_waf                = false
create_global_waf                  = false
ENABLE_POINT_IN_TIME_RECOVERY      = true
S3_LOGGING_BUCKET                  = "vap-dani-s3-test-logging"
# TRUSTED_ROLE_ACTIONS               = ["sts:AssumeRole"]
# TRUSTED_ROLE_ARNS                  = 