variable "RESOURCE_PREFIX" {}
variable "DEV_PORTAL_PRE_LOGIN_ACCOUNTS_TABLE_NAME" {}
variable "DEV_PORTAL_CUSTOMERS_TABLE_NAME" {}
variable "API_PERMISSION_TABLE_NAME" {}
variable "MNO_THIRD_PARTY_RESOURCE_TABLE_NAME" {}

variable "DEV_PORTAL_FEEDBACK_TABLE_NAME" {}
variable "ENABLE_POINT_IN_TIME_RECOVERY" {}
variable "KMS_KEY_ARN" {}